app/routes.py
# Standard Library imports

# Core Flask imports
from flask import Blueprint, render_template, request

# Third-party imports

# App imports
from app import db_manager
from app import login_manager
from .views import (
    error_views,
    account_management_views,
    static_views,
)
from .models import User, Uzivatele

bp = Blueprint('routes', __name__)

# alias
db = db_manager.session
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, PasswordField, BooleanField, SubmitField, DateField
from wtforms.validators import DataRequired, Email, EqualTo, Length, InputRequired, Regexp


class FormFormular(FlaskForm):
    name = StringField('Name', validators=[InputRequired(message="You can't leave this empty"),
                                           Length(min=2, max=20,
                                                  message="Name must be between 2 and 20 characters long"),
                                           Regexp('^[A-Za-z]*$', message="Name must contain only letters")])

    surename = StringField('Surename', validators=[InputRequired(message="You can't leave this empty"),
                                                   Length(min=2, max=20,
                                                          message="Name must be between 2 and 20 characters long"),
                                                   Regexp('^[A-Za-z]*$', message="Name must contain only letters")])


# List to store users
user_list = []


@bp.route("/formular", methods=["GET", "POST"])
def formular():
    user_list.clear()
    users = Uzivatele.query.all()
    for user in users:
        user_list.append({"user_id": user.user_id, "name": user.name, "surename": user.surename})
    form = FormFormular()
    if form.validate_on_submit():
        new_user = Uzivatele(name=form.name.data, surename=form.surename.data)
        db.add(new_user)
        db.commit()
        user_list.append({"user_id": new_user.user_id, "name": new_user.name, "surename": new_user.surename})
        return render_template("formular.html", form=form, users=user_list)
    return render_template("formular.html", form=form, users=user_list)


@bp.route("/edit_user/<int:user_id>", methods=["GET", "POST"])
def edit_user(user_id):
    user = Uzivatele.query.filter_by(user_id=user_id).first()
    form = FormFormular(obj=user)
    if form.validate_on_submit():
        user.name = form.name.data
        user.surename = form.surename.data
        db.commit()

        # Aktualizace seznamu uživatelů
        user_list.clear()
        users = Uzivatele.query.all()
        for user in users:
            user_list.append({"user_id": user.user_id, "name": user.name, "surename": user.surename})

        return render_template("formular.html", form=form, users=user_list)
    return render_template("formular.html", form=form, user=user)


@bp.route("/delete_user/<int:user_id>", methods=["GET", "POST"])
def delete_user(user_id):
    user = Uzivatele.query.filter_by(user_id=user_id).first()
    if user is None:
        # Aktualizace seznamu uživatelů
        user_list.clear()
        users = Uzivatele.query.all()
        for user in users:
            user_list.append({"user_id": user.user_id, "name": user.name, "surename": user.surename})
        return render_template("formular.html", form=FormFormular(), users=user_list)

    db.delete(user)
    db.commit()

    # Aktualizace seznamu uživatelů
    user_list.clear()
    users = Uzivatele.query.all()
    for user in users:
        user_list.append({"user_id": user.user_id, "name": user.name, "surename": user.surename})

    return render_template("formular.html", form=FormFormular(), users=user_list)


# Request management

@bp.before_app_request
def before_request():
    db()


# Request management
@bp.before_app_request
def before_request():
    db()


@bp.teardown_app_request
def shutdown_session(response_or_exc):
    db.remove()


@login_manager.user_loader
def load_user(user_id):
    """Load user by ID."""
    if user_id and user_id != "None":
        return User.query.filter_by(user_id=user_id).first()


# Error views
bp.register_error_handler(404, error_views.not_found_error)

bp.register_error_handler(500, error_views.internal_error)

# Public views
bp.add_url_rule("/", view_func=static_views.index)

bp.add_url_rule("/register", view_func=static_views.register)

bp.add_url_rule("/login", view_func=static_views.login)

# Login required views
bp.add_url_rule("/settings", view_func=static_views.settings)

# Public API
bp.add_url_rule(
    "/api/login", view_func=account_management_views.login_account, methods=["POST"]
)

bp.add_url_rule("/logout", view_func=account_management_views.logout_account)

bp.add_url_rule(
    "/api/register",
    view_func=account_management_views.register_account,
    methods=["POST"],
)

# Login Required API
bp.add_url_rule("/api/user", view_func=account_management_views.user)

bp.add_url_rule(
    "/api/email", view_func=account_management_views.email, methods=["POST"]
)

# Admin required
bp.add_url_rule("/admin", view_func=static_views.admin)

app/templates/admin.html
{% extends "base.html" %}

{% block content %}
    <h1>Admin</h1>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Application{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    {% block head %}{% endblock %}
</head>
<body>
    <div class="container d-flex kontejner">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

app/templates/formular.html
{% extends "base.html" %}

{% from "macros/fields.html" import render_input_field, render_submit %}

{% block title %}Formulář{% endblock %}

{% block content %}
  <div class="container d-flex kontejner">
    <div class="card">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h3 class="mb-0">Log In</h3>
        <a href="/formular" class="btn btn-custom">add new person</a>
      </div>
      <div class="card-body">
        <form method="POST" id='login-form'>
          {{ form.hidden_tag() }}
          {{ render_input_field(form.name, lc="col-sm-3", rc="col-sm-9") }}
          {{ render_input_field(form.surename, lc="col-sm-3", rc="col-sm-9") }}
          <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
              {{ render_submit(cls="btn btn-primary") }}
            </div>
          </div>
        </form>
        {% if message %}
          <div class="alert alert-info mt-3" role="alert">
            {{ message }}
          </div>
        {% endif %}
      </div>
    </div>
    <div class="card mt-5">
      <div class="card-header">
        <h3 class="mb-0">People list</h3>
      </div>
      <div class="card-body">
        <table class="table table-hover">
          <thead class="thead-light">
            <tr>
              <th>Name</th>
              <th>Surname</th>
            </tr>
          </thead>
          <tbody>
            {% for user in users %}
              <tr>
                <td>{{ user.name }}</td>
                <td>{{ user.surename }}</td>
                <td class="unvisible">
                  <a href="{{ url_for('routes.edit_user', user_id=user.user_id) }}" class="btn btn-edit btn-sm">Edit</a>
                  <a href="{{ url_for('routes.delete_user', user_id=user.user_id) }}" class="btn btn-delete btn-sm"><img class="obrazek"
                          src="https://cdn-icons-png.flaticon.com/512/1214/1214926.png " alt="delete-icon"></a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>flask_for_startups</h1>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>Login</h1>
    <form id="login_form">
        <div>
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required/>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" minlength="8" autocomplete="current-password" required/>
        </div>
        <button type="submit">login</button>
    </form>

    <script src="/static/js/login.js"></script>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block content %}
    <h1>Register</h1>
    <form id="register_form">
        <div>
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required/>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required/>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" minlength="8" autocomplete="current-password" required/>
        </div>

        <button type="submit">register</button>
    </form>


    <script src="/static/js/register.js"></script>
{% endblock %}

app/templates/settings.html
{% extends "base.html" %}

{% block content %}
    <h1>Settings</h1>
    <h2>Update your email</h2>
    <p>Your info:
        <br>
        <span id="current_email"></span>
        <br>
        <span id="current_username"></span>
    </p>
    <form id="settings_form">
        <label for="email">New email:</label>
        <input type="text" id="new_email" name="email"/>
        <br><br>
        <button type="submit">Update</button>
    </form>

    <script src="/static/js/settings.js"></script>
{% endblock %}